### ISSUE TITLE
latency-avg100000 does not exist

### ISSUE THREAD

**Issue by mtheofy** [johansaf/zabbix-template-dnsdist#1]
Hi,

thanks for publicising the template. I am using it but I noticed that latency-avg100000 does not exist. Correctly latency-avg1000000 exists. The problem is somehow present for the latency statistics for DoH and DoT i.e. latency-dot-avg100000 and latency-doh-avg100000 do not exist (both are missing an additional zero). I cross check this with dnsdist documentation [here](https://dnsdist.org/statistics.html).

Thanks again,
Marcos

**Comment by mtheofy** [comment]
Just noticed that the same applies for latency-tcp-avg100000

**Comment by JohanSaf** [comment]
Hi!

This is interesting, when looking at the documentation there are statistics for 10000 and 1000000, but not 100000 (lots of zeroes...). I also double-checked this against dnsdist directly and no values for 100000 are returned.

So the items you mention shouldn't be in the template. I'm a bit busy today but I'll try to get them removed tomorrow or friday.

Thanks!
